### ISSUE TITLE
太巧妙了，利用Prompt处理同步返回的问题

### ISSUE THREAD

**Issue by wcedla** [gtbluesky/dsbridge_flutter#1]
rt，给作者点赞，研究了半天这个同步返回不修改前端代码怎么实现，看到作者的仓库，真是惊喜

**Comment by gtbluesky** [comment]
用的感觉不错的话帮忙多宣传下，(#^.^#)

**Comment by wcedla** [comment]
试了下对ios的支持，ios不支持那三个dialog的实现，好像不能用啊

**Comment by gtbluesky** [comment]
肯定可以的，你直接跑example就行

**Comment by wcedla** [comment]
> 肯定可以的，你直接跑example就行

我们这边ios跑了demo，运行后提示platform没有实现那个prompt方法

**Comment by gtbluesky** [comment]
检查下lock文件，webview_flutter_wkwebview必须3.11.0以上

**Comment by gtbluesky** [comment]
![image](https://github.com/gtbluesky/dsbridge_flutter/assets/1782351/4f747b55-16c1-453f-890c-b2ffd4a03e74)

**Comment by wcedla** [comment]
> 检查下lock文件，webview_flutter_wkwebview必须3.11.0以上

升级wkwebview版本可以了，感谢，但是这个3.11.0对flutter版本要求太高了
