### ISSUE TITLE
运行demo，点击JavaScript call Dart会报错

### ISSUE THREAD

**Issue by xinjingshiran** [gtbluesky/dsbridge_flutter#2]
报错日志如下：

VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: UnimplementedError: setOnJavaScriptAlertDialog is not implemented on the current platform
#0      PlatformWebViewController.setOnJavaScriptAlertDialog (package:webview_flutter_platform_interface/src/platform_webview_controller.dart:303:5)
#1      new DWebViewController.fromPlatform (package:dsbridge_flutter/src/dsbridge_webview_controller.dart:66:14)
#2      new DWebViewController.fromPlatformCreationParams (package:dsbridge_flutter/src/dsbridge_webview_controller.dart:51:13)
#3      _JsCallDartPageState.initState (package:example/js_call_dart_page.dart:36:28)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5430:55)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273:5)
#6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182:16)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3707:18)
#8      SingleChildRenderObjectElement.mount (packag<…>
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: UnimplementedError: setOnJavaScriptConfirmDialog is not implemented on the current platform
#0      PlatformWebViewController.setOnJavaScriptConfirmDialog (package:webview_flutter_platform_interface/src/platform_webview_controller.dart:313:5)
#1      new DWebViewController.fromPlatform (package:dsbridge_flutter/src/dsbridge_webview_controller.dart:73:14)
#2      new DWebViewController.fromPlatformCreationParams (package:dsbridge_flutter/src/dsbridge_webview_controller.dart:51:13)
#3      _JsCallDartPageState.initState (package:example/js_call_dart_page.dart:36:28)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5430:55)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273:5)
#6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182:16)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3707:18)
#8      SingleChildRenderObjectElement.mount (pa<…>
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: UnimplementedError: setOnJavaScriptTextInputDialog is not implemented on the current platform
#0      PlatformWebViewController.setOnJavaScriptTextInputDialog (package:webview_flutter_platform_interface/src/platform_webview_controller.dart:323:5)
#1      new DWebViewController.fromPlatform (package:dsbridge_flutter/src/dsbridge_webview_controller.dart:81:14)
#2      new DWebViewController.fromPlatformCreationParams (package:dsbridge_flutter/src/dsbridge_webview_controller.dart:51:13)
#3      _JsCallDartPageState.initState (package:example/js_call_dart_page.dart:36:28)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5430:55)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273:5)
#6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182:16)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3707:18)
#8      SingleChildRenderObjectElement.mount<…>

**Comment by gtbluesky** [comment]
#1 参考下这个，注意版本

**Comment by xinjingshiran** [comment]
说个题外话，请问一下，什么时候能够适配鸿蒙呢？（鸿蒙flutter 版本3.7.12）

**Comment by gtbluesky** [comment]
应该不会太久，半个月左右吧

**Comment by xinjingshiran** [comment]
> 应该不会太久，半个月左右吧

辛苦大佬～
