### ISSUE TITLE
iOS上报错，js和dart相互调用没有效果

### ISSUE THREAD

**Issue by andysinlight** [gtbluesky/dsbridge_flutter#3]
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.5.2 22G91 darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: UnimplementedError: setOnJavaScriptAlertDialog is not implemented on the current platform
#0      PlatformWebViewController.setOnJavaScriptAlertDialog (package:webview_flutter_platform_interface/src/platform_webview_controller.dart:303:5)
#1      new DWebViewController.fromPlatform (package:dsbridge_flutter/src/dsbridge_webview_controller.dart:66:14)
#2      new DWebViewController.fromPlatformCreationParams (package:dsbridge_flutter/src/dsbridge_webview_controller.dart:51:13)
#3      _JsCallDartPageState.initState (package:example/js_call_dart_page.dart:36:28)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5430:55)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273:5)
#6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182:16)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3707:18)

**Comment by gtbluesky** [comment]
请参考 #1
